version: 2.1

orbs:
 android: circleci/android@0.2.0

jobs:
  build:
    working_directory: ~/react-native-simple/android
    executor: android/android
    
    steps:
      - checkout
      - run:
          command: ./gradlew build
